module initialization_module

struct microstate # holds the variables of the actual current or proposed state
    N::Int
    λ::Int 
    r_box::Matrix{Float64}
    r_frac_box::MVector{3,Float64}
end

function load_configuration(filename)
    # Loads in a cnf.inp file generated by Allen and Tildesly's initialize.py 
    # returns the first line, which has the number of particles in the configuration as N 
    # returns L, the box length which is from the second line 
    # returns r, the coordinates of the particles as a 3xN array:
#                       # r_N = [ x1  x2  x3 ... x_N
#                                 y1  y2  y3 ... y_N
#                                 z1  z2  z3 ... z_N ]
    # even though in the file cnf.inp it is stored as an Nx3 array 
    open(filename, "r") do io
        # Read N (int)
        N = parse(Int, strip(readline(io)))

        # Read L (float)
        L = parse(Float64, strip(readline(io)))

        # Read N lines of 3 floats each
        data = Array{Float64}(undef, N, 3)
        for i in 1:N
            data[i, :] = parse.(Float64, split(readline(io)))
        end

        # Transpose to 3×N (your preferred format)
        r = permutedims(data)   # or data' gives 3×N Float64 matrix
        return N, L, r
    end
end # load_configuration(filename)


end
